apiVersion: v1
kind: Service
metadata:
  name: regapp-service-gita
  labels:
    app: regapp-gita
  namespace: default
spec:
  selector:
    app: regapp-gita 

  ports:
    - port: 8092
      targetPort: 8080

  type: LoadBalancer
