apiVersion: v1
kind: Service
metadata:
  name: regapp-service-gita
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 8092
      targetPort: 8080

  type: LoadBalancer
